### ISSUE TITLE
ECDSA test fails

### ISSUE THREAD

**Issue by l-ko** [PeculiarVentures/node-webcrypto-p11#10]
EC
    2) Ecdsa
    ✓ ECDSA JWK export/import
    ✓ Ecdh

**Comment by microshine** [comment]
Which HSM do you use?

**Comment by rmhrisk** [comment]
SoftHSM

**Comment by l-ko** [comment]
library: '/usr/local/lib/softhsm/libsofthsm2.so'
      name: 'SoftHSM v2.0'
      slot: 0
      sessionFlags: 4
