### ISSUE TITLE
ecdh derivekey

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/node-webcrypto-p11#3]
https://github.com/aquto/strongswan/blob/a2924cd4bb4c86b6317bb5c22f445dab43e7a2c9/src/libstrongswan/plugins/pkcs11/pkcs11_dh.c

**Comment by microshine** [comment]
Derive keys - https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/test/ec.js#L71
Derive bits - https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/test/ec.js#L99
