### ISSUE TITLE
Openssl engine support

### ISSUE THREAD

**Issue by batuhanceylan** [PeculiarVentures/node-webcrypto-p11#46]
Hi,

I'm currently working on a project that makes TLS mutual authentication. The keys reside inside HSM. Do you have any information whether it is possible to do TLS client authentication with this package?

**Comment by rmhrisk** [comment]
node-webcrypto-p11 would be useful to your task if you had a TLS implementation based on WebCrypto. I am not aware of such a library.

You want to work with crypto.setEngine() in node; see https://github.com/nodejs/node/issues/5101

**Comment by batuhanceylan** [comment]
Thank you. I'll check it out.
