### ISSUE TITLE
User Pin dialogue

### ISSUE THREAD

**Issue by abrbhat** [PeculiarVentures/node-webcrypto-p11#47]
I am getting this dialog box when trying to sign using MSCAPI. Is this generated by node-webcrypto-p11? If yes, where is the source?

![image](https://user-images.githubusercontent.com/4189727/57030748-6eeb7e80-6c63-11e9-975f-a639f36d26ab.png)

**Comment by rmhrisk** [comment]
This is generated by the CSP.

**Comment by abrbhat** [comment]
Got it. Thanks @rmhrisk
