### ISSUE TITLE
Exporting Certificate Chain

### ISSUE THREAD

**Issue by abrbhat** [PeculiarVentures/node-webcrypto-p11#51]
Is there a way to extract certificate chain from the hardware token through this library?

**Comment by rmhrisk** [comment]
Yes. 

https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/src/cert.ts#L104

**Comment by abrbhat** [comment]
Thought so. Fetching through AIA now. Thanks for the reply and for this amazing project!
