### ISSUE TITLE
CKR_ATTRIBUTE_VALUE_INVALID:19 (Safenet Luna Thales HSM) on AES Key creation

### ISSUE THREAD

**Issue by furio** [PeculiarVentures/node-webcrypto-p11#63]
Hi

I'm using the library in conjuction with a Safenet Luna ( `libCryptoki2_64.so` )
If i do: 
` const key = await crypto.subtle.generateKey({name: "AES-GCM", length: 256}, true, ["encrypt", "decrypt"]);`

I get
```
CryptoError: Aes: Can not generate new key
CKR_ATTRIBUTE_VALUE_INVALID:19
    at Error (native) C_GenerateKey:893
    at /softhsm-tests/node_modules/node-webcrypto-p11/build/cjs/mechs/aes/crypto.js:48:32
    at /softhsm-tests/node_modules/graphene-pk11/build/cjs/session.js:130:25
```

Fiddling a bit with the options sent to HSM in the `class AesCrypto`.`generateKey` method if i remove the `sensitive` attribute from
```
{
  token: false,
  label: 'AES-256',
  id: <Buffer f3 f7 67 96 e9 ab ea ed b0 30 5b 72 d1 00 bd b9 75 26 92 e1>,
  class: 4,
  sensitive: false,
  extractable: true,
  derive: false,
  sign: false,
  verify: false,
  decrypt: true,
  encrypt: true,
  unwrap: false,
  wrap: false,
  keyType: 31,
  valueLen: 32
}
```

The key is created without any error.

**Comment by furio** [comment]
Just to leave a note, I've implemented this workaround by following issue #61 :

```
class CustomTemplateBuilder {
    setOldConstructor(old) {
        this.old = old;
    }

    build(parameters) {
        let result = this.old.build(parameters);
        switch (parameters.type) {
            case "secret": {
                if (result.label.indexOf("AES") != -1)
                    delete result.sensitive;
                break;
            }

            default:
                break;
        }
        return result;
    }
}

const crypto = new Crypto(config);
const newTemplateBuilder =  new CustomTemplateBuilder();
newTemplateBuilder.setOldConstructor(crypto.templateBuilder);
crypto.templateBuilder = newTemplateBuilder;
```

**Comment by rmhrisk** [comment]
Hrm.... 

In general, these attributes mean that the actual value of the secret key is not to be exposed. It is really odd this is not working, especially since we have done basic interoperability testing with SafeNet HSMs in the past.

Are you sure you are running the latest middleware?

**Comment by furio** [comment]
Node.js dependencies:
```
    "dependencies": {
        "node-webcrypto-p11": "2.3.5"
    }
```

Luna: `Client_SDK_SafeNet_HSM_7.4.1-2` for Linux

**Comment by rmhrisk** [comment]
Ah, that makes sense, the HSM requires sensitive. I think all of this is then by design and not something that needs to be changed.
