### ISSUE TITLE
RSASSA-PKCS1-v1_5 2048 generation

### ISSUE THREAD

**Issue by l-ko** [PeculiarVentures/node-webcrypto-p11#9]
Can not generate a key with params same as for ossl
```
[Error: Pkcs11Error: Error in C_GenerateKeyPair function ATTRIBUTE_VALUE_INVALID(19)]
  message: 'Pkcs11Error: Error in C_GenerateKeyPair function ATTRIBUTE_VALUE_INVALID(19)',
  code: 19,
  func: 'C_GenerateKeyPair',
  stack: 'Error: Pkcs11Error: Error in C_GenerateKeyPair function ATTRIBUTE_VALUE_INVALID(19)\n    at new Pkcs11Error (/root/node-webcrypto-p11/node_modules/graphene-pk11/build/core/error.js:14:23)\n    at /root/node-webcrypto-p11/node_modules/graphene-pk11/build/session.js:225:38\n    at /root/node-webcrypto-p11/node_modules/graphene-pk11/node_modules/ffi/lib/_foreign_function.js:115:9' }
Error: Pkcs11Error: Error in C_GenerateKeyPair function ATTRIBUTE_VALUE_INVALID(19)
    at new Pkcs11Error (/root/node-webcrypto-p11/node_modules/graphene-pk11/build/core/error.js:14:23)
    at /root/node-webcrypto-p11/node_modules/graphene-pk11/build/session.js:225:38
    at /root/node-webcrypto-p11/node_modules/graphene-pk11/node_modules/ffi/lib/_foreign_function.js:115:9
```

**Comment by microshine** [comment]
Can you show log of incoming params?

**Comment by l-ko** [comment]
{ algorithm: 
      { name: 'RSASSA-PKCS1-v1_5',
        modulusLength: 2048,
        publicExponent: [Object],
        hash: [Object] },
     usages: [ 'sign', 'verify' ],
     owners: [ 'udS26MEXiMDMqCcTRPRoYYlZvIOelcg-5u2MzHxAX_KXyGrnMzyfnQU1jEV3ZaT8-t8-XhycPIyzUDWiRO2d_EJG33ccFoIauikJ4KK_1rq15N5MEUWYTPRZKmvZmfSLTRFVyyb6Do-mKpfEucxwXdCeFgFledbDh5D9tnYLbgZ398xl_TksLqvj59rsF1TyggDIxNPFIWLHusY3mLReMzvChROkbVu_JSZ4Wnr9iswSOUhh5EQwND8AYbkTMGSaGuTh66N7so_zgI1MN_oVLrIOd52re_Yl32QTS550QLbfogtB8kaQX49HU0mWen8f-8H9zLjm040E2OI1XvBnNQ' ],
     users: [],
     ttl: 1800000,
     extractable: false }

**Comment by l-ko** [comment]
Loos like it was mine bug, because I've setted extractable to undefined. I guess that was a reason for the error, however, ossl does not care about it
